version: "3.1"

services:
  php-apache:
    container_name: 'web-gateway'
    build:
      args:
        container_project_path: /var/www/html/
        uid: 1000
        user: $USER
      context: .
      dockerfile: ./Dockerfile
    networks:
      - accounts
    ports:
      - "80:80"
    volumes:
      - ./workspace/:/var/www/html/

networks:
  accounts:
    driver: "bridge"
